
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Val
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bsolo = new javax.swing.JButton();
        Bmulti = new javax.swing.JButton();
        Bquitter = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCharger = new javax.swing.JMenuItem();
        jMenuItemOptions = new javax.swing.JMenuItem();
        jMenuItemQuitter = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemRegles = new javax.swing.JMenuItem();
        jMenuItemAPropos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bridge Chinois");
        setBackground(new java.awt.Color(255, 204, 204));
        setBounds(new java.awt.Rectangle(200, 200, 0, 0));
        setForeground(new java.awt.Color(255, 204, 204));
        setResizable(false);
        getContentPane().setLayout(null);

        Bsolo.setText("Jouer contre l'ordinateur");
        Bsolo.setMaximumSize(new java.awt.Dimension(125, 23));
        Bsolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsoloActionPerformed(evt);
            }
        });
        getContentPane().add(Bsolo);
        Bsolo.setBounds(80, 100, 185, 25);

        Bmulti.setText("Jouer en ligne");
        Bmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmultiActionPerformed(evt);
            }
        });
        getContentPane().add(Bmulti);
        Bmulti.setBounds(80, 170, 185, 25);

        Bquitter.setText("Quitter");
        Bquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BquitterActionPerformed(evt);
            }
        });
        getContentPane().add(Bquitter);
        Bquitter.setBounds(80, 300, 185, 25);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(80, 290, 185, 10);

        jButton1.setText("Jouer à 2 joueurs");
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 130, 185, 25);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(80, 240, 185, 10);

        jButton3.setText("Charger une partie");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(80, 200, 185, 25);

        jButton4.setText("Apprendre à jouer");
        getContentPane().add(jButton4);
        jButton4.setBounds(80, 250, 185, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/bridge.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 30, 260, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/menu.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 390);

        jMenu1.setText("Menu");

        jMenuItemCharger.setText("Charger");
        jMenuItemCharger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChargerActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCharger);

        jMenuItemOptions.setText("Options");
        jMenuItemOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOptionsActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOptions);

        jMenuItemQuitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemQuitter.setMnemonic('Q');
        jMenuItemQuitter.setText("Quitter");
        jMenuItemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitterActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemQuitter);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("?");

        jMenuItemRegles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemRegles.setText("Règles");
        jMenuItemRegles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReglesActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRegles);

        jMenuItemAPropos.setText("A propos");
        jMenuItemAPropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAProposActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAPropos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-349)/2, (screenSize.height-432)/2, 349, 432);
    }// </editor-fold>//GEN-END:initComponents

    private void BsoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsoloActionPerformed
        // TODO add your handling code here:
        VSIA fenOp = new VSIA();
        fenOp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BsoloActionPerformed

    private void BquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BquitterActionPerformed
        // TODO add your handling code here:
        
        Confirmation a = new Confirmation(this,true,"Voulez vous vraiment quitter ?");
        a.setVisible(true);
        
        if (a.getReturnStatus()==1)
            this.dispose();
            
        
    }//GEN-LAST:event_BquitterActionPerformed

    private void BmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmultiActionPerformed
        // TODO add your handling code here:
        
        Multi mul = new Multi();
        mul.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BmultiActionPerformed

    private void jMenuItemReglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReglesActionPerformed
        // TODO add your handling code here:
        Regle reg = new Regle(this,true);
        reg.setVisible(true);
    }//GEN-LAST:event_jMenuItemReglesActionPerformed

    private void jMenuItemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitterActionPerformed
        // TODO add your handling code here:
        Confirmation a = new Confirmation(this,true,"Voulez vous vraiment quitter ?");
        a.setVisible(true);
        
        if (a.getReturnStatus()==1)
            this.dispose();
    }//GEN-LAST:event_jMenuItemQuitterActionPerformed

    private void jMenuItemOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOptionsActionPerformed
        // TODO add your handling code here:
        
    	Option opt = new Option();
        opt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemOptionsActionPerformed

    private void jMenuItemAProposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAProposActionPerformed
        // TODO add your handling code here:
        Apropos propo = new Apropos(this,true);
        propo.setVisible(true);
    }//GEN-LAST:event_jMenuItemAProposActionPerformed

    private void jMenuItemChargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChargerActionPerformed
        // TODO add your handling code here:
        Charge file = new Charge(this,true);
        file.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jMenuItemChargerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Charge file = new Charge(this,true);
        file.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bmulti;
    private javax.swing.JButton Bquitter;
    private javax.swing.JButton Bsolo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAPropos;
    private javax.swing.JMenuItem jMenuItemCharger;
    private javax.swing.JMenuItem jMenuItemOptions;
    private javax.swing.JMenuItem jMenuItemQuitter;
    private javax.swing.JMenuItem jMenuItemRegles;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
