/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Amine
 */
public class Options extends javax.swing.JDialog {

    /**
     * Creates new form Options
     */
    public Options(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTheme = new javax.swing.ButtonGroup();
        buttonGroupCartes = new javax.swing.ButtonGroup();
        conf = new Config();
        jButtonAnnuler = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxAnciensPlis = new javax.swing.JCheckBox();
        jCheckBoxCartesAdv = new javax.swing.JCheckBox();
        jLabelCheat = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonTheme1 = new javax.swing.JRadioButton();
        jRadioButtonTheme2 = new javax.swing.JRadioButton();
        jLabelTheme = new javax.swing.JLabel();
        jRadioButtonTheme3 = new javax.swing.JRadioButton();
        jCheckBoxSon = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelCartes = new javax.swing.JLabel();
        jRadioButtonCartes1 = new javax.swing.JRadioButton();
        jRadioButtonCartes2 = new javax.swing.JRadioButton();
        jRadioButtonCartes3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnnuler);
        jButtonAnnuler.setBounds(20, 510, 78, 23);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOK);
        jButtonOK.setBounds(370, 510, 47, 23);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jCheckBoxAnciensPlis.setText("Voir anciens plis");
        jCheckBoxAnciensPlis.setSelected(conf.isVoitPlis());
        jPanel1.add(jCheckBoxAnciensPlis);
        jCheckBoxAnciensPlis.setBounds(62, 54, 120, 23);

        jCheckBoxCartesAdv.setText("Voir cartes adversaire");
        jCheckBoxCartesAdv.setSelected(conf.isVoitCartes());
        jPanel1.add(jCheckBoxCartesAdv);
        jCheckBoxCartesAdv.setBounds(62, 28, 150, 23);

        jLabelCheat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCheat.setText("Possibilitée de triche :");
        jPanel1.add(jLabelCheat);
        jLabelCheat.setBounds(60, 10, 140, 14);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/option_theme.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 300, 90);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 320, 300, 90);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        buttonGroupTheme.add(jRadioButtonTheme1);
        jRadioButtonTheme1.setText("Vert");
        if (conf.getStyle() == 1)
        jRadioButtonTheme1.setSelected(true);
        jPanel2.add(jRadioButtonTheme1);
        jRadioButtonTheme1.setBounds(60, 40, 45, 23);

        buttonGroupTheme.add(jRadioButtonTheme2);
        jRadioButtonTheme2.setText("Bleu");
        if (conf.getStyle() == 2)
        jRadioButtonTheme2.setSelected(true);
        jPanel2.add(jRadioButtonTheme2);
        jRadioButtonTheme2.setBounds(140, 40, 60, 23);

        jLabelTheme.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTheme.setText("Thèmes de la table :");
        jPanel2.add(jLabelTheme);
        jLabelTheme.setBounds(90, 10, 120, 14);

        buttonGroupTheme.add(jRadioButtonTheme3);
        if (conf.getStyle() == 3)
        jRadioButtonTheme3.setSelected(true);
        jRadioButtonTheme3.setText("Metal");
        jPanel2.add(jRadioButtonTheme3);
        jRadioButtonTheme3.setBounds(220, 40, 51, 23);

        jCheckBoxSon.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxSon.setSelected(conf.isSon());
        jCheckBoxSon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSonActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxSon);
        jCheckBoxSon.setBounds(110, 80, 20, 20);

        jLabel5.setText("Activation du son :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 80, 100, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/option_theme.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 300, 120);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(70, 40, 300, 110);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jLabelCartes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCartes.setText("Thèmes des cartes :");
        jPanel3.add(jLabelCartes);
        jLabelCartes.setBounds(80, 10, 120, 14);

        buttonGroupCartes.add(jRadioButtonCartes1);
        jRadioButtonCartes1.setText("Anciennes");
        if (conf.getDeck() == 2)
        jRadioButtonCartes1.setSelected(true);
        jPanel3.add(jRadioButtonCartes1);
        jRadioButtonCartes1.setBounds(20, 40, 90, 23);

        buttonGroupCartes.add(jRadioButtonCartes2);
        jRadioButtonCartes2.setText("Nouvelles");
        if (conf.getDeck() == 1)
        jRadioButtonCartes2.setSelected(true);
        jPanel3.add(jRadioButtonCartes2);
        jRadioButtonCartes2.setBounds(130, 40, 80, 23);

        buttonGroupCartes.add(jRadioButtonCartes3);
        jRadioButtonCartes3.setText("Chats");
        if (conf.getDeck() == 3)
        jRadioButtonCartes3.setSelected(true);
        jPanel3.add(jRadioButtonCartes3);
        jRadioButtonCartes3.setBounds(230, 40, 70, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(70, 180, 300, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/option_theme.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 180, 300, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/options.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 570);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-472)/2, (screenSize.height-598)/2, 472, 598);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonAnnulerActionPerformed
    
    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonCartes1.isSelected()) {
            conf.setDeck(2);
        } else if (jRadioButtonCartes2.isSelected()) {
            conf.setDeck(1);
        } else if (jRadioButtonCartes3.isSelected()) {
            conf.setDeck(3);
        }
        if (jRadioButtonTheme1.isSelected()) {
            conf.setStyle(1);
        } else if (jRadioButtonTheme2.isSelected()) {
            conf.setStyle(2);
        } else if (jRadioButtonTheme3.isSelected()) {
            conf.setStyle(3);
        }
        conf.setVoitCartes(jCheckBoxCartesAdv.isSelected());
        conf.setVoitPlis(jCheckBoxAnciensPlis.isSelected());
        conf.setSon(jCheckBoxSon.isSelected());
        conf.saveConfigs();
        this.dispose();
        
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jCheckBoxSonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                Options dialog = new Options(new javax.swing.JFrame(), true);
                conf = new Config();
                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private static Config conf;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCartes;
    private javax.swing.ButtonGroup buttonGroupTheme;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JCheckBox jCheckBoxAnciensPlis;
    private javax.swing.JCheckBox jCheckBoxCartesAdv;
    private javax.swing.JCheckBox jCheckBoxSon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCartes;
    private javax.swing.JLabel jLabelCheat;
    private javax.swing.JLabel jLabelTheme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonCartes1;
    private javax.swing.JRadioButton jRadioButtonCartes2;
    private javax.swing.JRadioButton jRadioButtonCartes3;
    private javax.swing.JRadioButton jRadioButtonTheme1;
    private javax.swing.JRadioButton jRadioButtonTheme2;
    private javax.swing.JRadioButton jRadioButtonTheme3;
    // End of variables declaration//GEN-END:variables
}
