    /*
* To change this template, choose Tools | Templates
* and open the template in the editor.
*/

import java.awt.Color;

import javax.swing.SwingUtilities;

/**
*
* @author Val
*/
public class VSPlayer extends javax.swing.JFrame {
    String ip;
    String host;

    /**
* Creates new form VSPlayer
*/
    public VSPlayer(String ip, String host) {
this.ip = ip;
this.host = host;
        initComponents();
    }

    /**
* This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor.
*/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Launch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nbParties = new javax.swing.JComboBox();
        mode = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Jouer en ligne");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        Launch.setText("Démarrer");
        Launch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaunchActionPerformed(evt);
            }
        });
        getContentPane().add(Launch);
        Launch.setBounds(220, 80, 90, 23);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        nbParties.setEditable(true);
        nbParties.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "3", "5", "10" }));
        nbParties.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nbPartiesFocusLost(evt);
            }
        });
        jPanel1.add(nbParties);
        nbParties.setBounds(196, 12, 65, 20);

        mode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre de Donnes", "Nombre de Plis" }));
        jPanel1.add(mode);
        mode.setBounds(11, 12, 150, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/option_theme.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 280, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 20, 280, 40);

        Cancel.setText("Annuler");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(30, 80, 80, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/menu.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/menu.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 380, 140);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-358)/2, (screenSize.height-165)/2, 358, 165);
    }// </editor-fold>//GEN-END:initComponents

    private void nbPartiesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nbPartiesFocusLost
        // TODO add your handling code here:
        if (nbParties.getSelectedItem() instanceof Integer) {
            nbParties.setBackground(Color.white);


        } else {
            nbParties.setBackground(Color.red);


        }
    }//GEN-LAST:event_nbPartiesFocusLost

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        // Confirmation a = new Confirmation(this, true, "Revenir au menu ?");
        // a.setVisible(true);

        // if (a.getReturnStatus() == 1) {
        Multi m = new Multi();
        m.setVisible(true);
        this.dispose();
        // }
    }//GEN-LAST:event_CancelActionPerformed

    private void LaunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaunchActionPerformed
        // TODO add your handling code here:
// on ferme la fenetre de menu


    this.dispose();
    new Thread(new Runnable() {
    public void run() {
final int mod = mode.getSelectedIndex();
final int nbPart = Integer.parseInt((String)nbParties.getSelectedItem());
Table table = new Table();
Moteur moteur = new Moteur(table);
Jeu monJeu = new Jeu(moteur, 2, mod, nbPart, 0, false);
monJeu.attachDistantPlayer(ip, true);
System.out.println();
final Graphique gg = new Graphique(monJeu);
monJeu.addObservateur(new Observateur() {
public void update(Jeu jeu) {
gg.getZoneDessin().repaint();
}
});
SwingUtilities.invokeLater(gg);
monJeu.jouer();
}
        }).start();


    }//GEN-LAST:event_LaunchActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        // Confirmation a = new Confirmation(this, true, "Revenir au menu ?");
        // a.setVisible(true);

        // if (a.getReturnStatus() == 1) {
        Multi mul = new Multi();
        mul.setVisible(true);
        this.dispose();
        //}
    }//GEN-LAST:event_formWindowClosing

    /**
* @param args the command line arguments
*/
    public static void main(String args[]) {
        /*
* Set the Nimbus look and feel
*/
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
* If Nimbus (introduced in Java SE 6) is not available, stay with the
* default look and feel. For details see
* http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VSPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VSPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VSPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VSPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
* Create and display the form
*/
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VSPlayer("","").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Launch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox mode;
    private javax.swing.JComboBox nbParties;
    // End of variables declaration//GEN-END:variables
}
